### ISSUE TITLE
Issue with World.py

### ISSUE THREAD

**Issue by jamieroderick** [jseidl/virtuaplant#5]
Hi,
I have been having some issues when trying to run the start.sh. The bottling plant pane is a black window and I get the following exception:

VirtuaPlant -- Bottle-filling Factory
- Starting World View
- Starting HMI
jamie@jamie-virtual-machine:~/Desktop/virtuaplant-master/plants/bottle-filling$ Loading chipmunk for Linux (64bit) [/usr/local/lib/python2.7/dist-packages/pymunk/libchipmunk.so]
INFO:pymodbus.server.async:Starting Modbus TCP Server on localhost:5020
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "./world.py", line 213, in runWorld
    space.add_collision_handler(0x1, 0x2, begin=bottle_in_place)
exceptions.TypeError: add_collision_handler() got an unexpected keyword argument 'begin'

I am definitely not an expert when it comes to Linux - grateful for any help I get with this.

Thanks.
Jamie

**Comment by jamieroderick** [comment]
Fixed it....my bad.

**Comment by jseidl** [comment]
Hi Jamie. Glad you managed to solve it. Can you share in this issue what
was the matter so if future people have this problem they can find the
solution?

Regards,
Jan

**Comment by jamieroderick** [comment]
The issue related to establishing communications between the server and HMI. The linux distro was separately reporting an insecure version of OpenSSL library and so would not permit the connection to be established, even on local host. This was on a Ubuntu 14.04 linux build. I re-installed the cryptography library using PIP

sudo pip install cryptography

I then did a sanity check of the other dependencies which all reported current versions. The world and him python scripts then ran correctly.

Jamie
